"use client";

import { useState, useTransition } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Archive, ChevronRight, ClipboardCheck, PackagePlus, Plus } from "lucide-react";
import type { Equipment, Shoot } from "@/lib/admin/pre-shoot";
import { addShootEquipment, archiveEquipment, createShoot, loadKit } from "@/lib/admin/pre-shoot-actions";
import s from "./admin.module.css";

type Props = { equipment: Equipment[]; kits: { id: string; name: string }[]; shoots: Shoot[]; projects: { id: string; title: string | null; project_type: string | null }[]; clients: { id: string; name: string }[] };
const format = (iso: string) => new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(iso));
export function PreShootManager({ equipment, kits, shoots, projects, clients }: Props) {
  const router = useRouter(); const [pending, start] = useTransition(); const [open, setOpen] = useState<string | null>(null); const [message, setMessage] = useState("");
  const submitShoot = (fd: FormData) => start(async () => { const result = await createShoot(fd); if (!result.ok) return setMessage(result.error ?? "Could not create shoot."); router.push(`/admin/pre-shoot/${result.id}`); });
  const addGear = (shootId: string, equipmentId: string) => start(async () => { await addShootEquipment(shootId, equipmentId); router.push(`/admin/pre-shoot/${shootId}`); });
  return <div className={s.preShootPage}>
    <header className={s.pageHead}><div><p className={s.eyebrow}>Production readiness</p><h1 className={s.title}>Pre-Shoot Check</h1><p className={s.subtitle}>The fast answer to “do I have everything?”</p></div><button className={s.button} onClick={() => setOpen(open === "shoot" ? null : "shoot")}><Plus size={16} />Quick shoot</button></header>
    {message && <p className={`${s.notice} ${s.noticeBad}`}>{message}</p>}
    {open === "shoot" && <form className={`${s.card} ${s.form}`} action={submitShoot}><div className={s.cardHead}><h2 className={s.cardTitle}>Quick shoot</h2><span className={s.metaText}>No project required</span></div><div className={s.formGrid}><label className={s.field}>Shoot name<input className={s.input} name="name" required placeholder="Music Video — Sketxa" /></label><label className={s.field}>Date & call time<input className={s.input} name="shoot_at" type="datetime-local" required /></label><label className={s.field}>Location<input className={s.input} name="location" placeholder="Boston, MA" /></label><label className={s.field}>Shoot type<input className={s.input} name="shoot_type" placeholder="Music video" /></label><label className={s.field}>Client (optional)<select className={s.input} name="client_id" defaultValue=""><option value="">No client</option>{clients.map((c) => <option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label className={s.field}>Project (optional)<select className={s.input} name="project_id" defaultValue=""><option value="">No project</option>{projects.map((p) => <option value={p.id} key={p.id}>{p.title ?? p.project_type ?? "Untitled project"}</option>)}</select></label><label className={`${s.field} ${s.fieldWide}`}>Shot list / treatment link (optional)<input className={s.input} name="shot_list_url" type="url" placeholder="https://milanote.com/..." /></label></div><button className={s.button} disabled={pending} type="submit">Create and choose gear</button></form>}
    <section className={s.shootList}><div className={s.cardHead}><h2 className={s.cardTitle}>Upcoming & recent shoots</h2><Link className={s.cardLink} href="/admin/equipment">Manage inventory <ChevronRight size={14} /></Link></div>{shoots.length ? shoots.map((shoot) => <article className={s.shootCard} key={shoot.id}><div><span className={`${s.badge} ${shoot.status === "ready" ? s.toneGood : shoot.status === "not_started" ? s.toneMuted : s.toneWarn}`}>{shoot.status.replace(/_/g, " ")}</span><h2>{shoot.name}</h2><p>{format(shoot.shoot_at)}{shoot.location ? ` · ${shoot.location}` : ""}</p></div><div className={s.shootActions}><Link className={s.button} href={`/admin/pre-shoot/${shoot.id}`}><ClipboardCheck size={16} />{shoot.status === "not_started" ? "Start pre-shoot check" : "Continue"}</Link><button className={`${s.button} ${s.buttonGhost}`} onClick={() => setOpen(open === shoot.id ? null : shoot.id)}><PackagePlus size={16} />Add gear</button></div>{open === shoot.id && <div className={s.gearPicker}><div><b>Gear for this shoot</b><p>Only selected equipment appears in the checklist.</p></div>{kits.length > 0 && <div className={s.kitButtons}>{kits.map((kit) => <button className={`${s.button} ${s.buttonGhost}`} disabled={pending} key={kit.id} onClick={() => start(async () => { await loadKit(shoot.id, kit.id); router.push(`/admin/pre-shoot/${shoot.id}`); })}>Load {kit.name}</button>)}</div>}<div className={s.gearPickerList}>{equipment.filter((e) => e.active).map((e) => <button disabled={pending} key={e.id} onClick={() => addGear(shoot.id, e.id)}><span><Plus size={14} /></span>{e.name}<small>{e.category}</small></button>)}</div></div>}</article>) : <div className={`${s.card} ${s.empty}`}><strong>No shoots yet</strong><span>Create a quick shoot to start a check — it can stay independent of projects.</span></div>}</section>
  </div>;
}
export function InventoryManager({ equipment, categories }: { equipment: Equipment[]; categories: readonly string[] }) {
  const [pending, start] = useTransition();
  return <div className={s.inventoryGrid}>{categories.map((category) => { const rows = equipment.filter((x) => x.category === category); return <details className={s.gearGroup} key={category} open={rows.length > 0}><summary>{category}<span>{rows.length}<ChevronRight size={16} /></span></summary>{rows.map((item) => <div className={s.inventoryRow} key={item.id}><span><b>{item.name}</b><small>{item.quantity} {item.quantity === 1 ? "item" : "items"}{item.required ? " · Required" : ""}{item.notes ? ` · ${item.notes}` : ""}</small></span><button className={s.linkButton} disabled={pending} onClick={() => start(async () => { await archiveEquipment(item.id, item.active); location.reload(); })}><Archive size={15} />{item.active ? "Deactivate" : "Archive"}</button></div>)}</details>; })}</div>;
}
